// Automatically generated by astro-icon
// 9bb22893e1f5163311ee5bf8e7f8071c3cbfdb480cebeeab8b8fcb488e03e074

declare module 'virtual:astro-icon' {
  export type Icon = 'github' | 'linkedin' | 'menu';
}
